# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    default: { url: "%env(ELASTICSEARCH_URL)%" }
  serializer: ~
  indexes:
    product:
      serializer:
        groups: [elastica]
      persistence:
        driver: orm
        model: App\Entity\Product
        provider: ~
        finder: ~
      properties:
        vendorProducts:
          type: "nested"
          properties:
            id:
              type: "long"
            price:
              type: "double" # Update type to double for price field
            quantity:
              type: "long"
            vendorId:
              type: "long"
